name: Worker Image Push

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'worker/**'
  push:
    branches: [main]
    paths:
      - 'worker/**'


permissions:
  contents: read
  pull-requests: read
  id-token: write  

jobs:
  docker-build:
    name: Docker Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t voting-app/worker:${{ github.sha }} ./worker

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: voting-app/worker:${{ github.sha }}
          format: table
          output: trivy-results.txt
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-image-scan
          path: trivy-results.txt

  docker-push:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: eu-west-2    

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: voting-app/worker
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:latest \
            ./worker

          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest



